### ISSUE TITLE
How to detect "institutional account" login?

### ISSUE THREAD

**Issue by windhamg** [lizkrznarich/orcid-demo-app#8]
I presume the `oauth-redirect-idp.php` script is for scenarios when the user is connecting an existing ORCiD ID and signs-in via an "institutional account". My question is: since I (as the developer) don't know which mechanisms ("personal" or "institutional") is going to be selected by the user when constructing the `https://orcid.org/oauth/authorize` link, how can I detect/handle "institutional account" logins within the redirect callback (e.g., present different confirmation/deny messages, as done in `oauth-redirect-idp.php` vs `oauth-redirect.php`)?

Thanks in advance for any assistance/pointers!

**Comment by lizkrznarich** [comment]
Hi there! In a typical OAuth interaction with the ORCID API, it's not possible to detect how the user signed into ORCID - however - we recently launched a new feature ('identity provider cross-link') that allows ORCID member orgs who use federated identity systems to automatically request ORCID iDs/record access permissions from users who sign in via their identity system.  In this case, we configure your API creds on our end with a separate redirect URI used only when users sign in via your institution.  Since your app knows that users can only hit that redirect via institutional account signin, you can tailor your messaging accordingly. ```oauth-redirect-idp.php``` was created so that we could demo the identity provider cross-link process, as described in https://github.com/ORCID/i2-workshop-2016 . If you'd like to try it out in the our [sandbox](https://sandbox.orcid.org/signin), email support@orcid.org with the [identity provider settings](https://github.com/ORCID/i2-workshop-2016#62-configure-identity-provider-settings-for-your-api-credentials) you'd like to use, and our support team will those settings to your sandbox API creds.
